SUPABASE_URL = "https://aexrxrhizqvkrhbyqsed.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFleHJ4cmhpenF2a3JoYnlxc2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjQxMzcsImV4cCI6MjA1ODMwMDEzN30.rzLHX6X47J2CzPwpCEvkXd_7QvORMadr7ETk-2gXyOE"
